# # This is a basic workflow to help you get started with Actions

# name: shop-stalk

# on:
#   push:
#     branches:
#       - main


# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout
#         uses: actions/checkout@v2


#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'temurin'
#           java-version: '11'


#       - name: Grant execute permission for gradlew
#         working-directory: ./
#         run: chmod +x ./gradlew
#         shell: bash


#       - name: Build with Gradle
#         working-directory: ./
#         run: ./gradlew build -x test
#         shell: bash


#       - name: Get current time
#         uses: josStorer/get-current-time@v2.0.0
#         id: current-time
#         with:
#           format: YYYY-MM-DDTHH-mm-ss # 다른 포맷으로 변경 가능
#           utcOffset: "+09:00" ## 한국시간에 맞추기 위함

      
#       # Gradle build를 통해 만들어진 JAR를 beanstalk에 배포하기 위한 ZIP 파일로 만드는 것
#       - name: Generate deployment package
#         run: |
#           mkdir -p deploy
#           cp build/libs/*.jar deploy/application.jar  # 빌드 완료 시 JAR 파일명을 application.jar로 변경
#           cp Procfile deploy/Procfile
#           cp -r .ebextensions deploy/.ebextensions
#           cp -r .platform deploy/.platform
#           cd deploy && zip -r deploy.zip . # Procfile, .ebextensions, .playform 포함하여 zip 생성


#       # Beanstalk Deploy 플러그인 사용
#       - name: Beanstalk Deploy
#         uses: einaregilsson/beanstalk-deploy@v20
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} # github secrets로 등록한 값 사용
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # github secrets로 등록한 값 사용
#           application_name: shop-stalk # EB application 이름
#           environment_name: Shopstalk-env # EB environment 이름
#           version_label: Github Action-${{steps.current-time.outputs.formattedTime}} # 배포 버전은 타임스탬프를 이용하여 구분
#           region: ap-northeast-2
#           deployment_package: deploy/deploy.zip
#           wait_for_environment_recovery: 180 # default wait time은 30초이며, 필자의 EB가 느려서 180초로 지정했습니다(지정 안하면 간혹 timeout 발생).
